# Generated by Django 2.0.7 on 2018-08-07 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified Time')),
                ('os', models.CharField(choices=[('ios', 'IOS'), ('android', 'Android')], max_length=8)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('arn', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_devices', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified Time')),
                ('notification_type', models.CharField(blank=True, max_length=255, null=True)),
                ('arn', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='sns_mobile_push_notification.Device')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
